### ISSUE TITLE
Assertion errors due to lack of encoding

### ISSUE THREAD

**Issue by augustd** [janeklb/gh-search#63]
Some results from github do not have the right encoding and this causes AssertionErrors: 

```
Traceback (most recent call last):                   
  File "/opt/homebrew/bin/gh-search", line 33, in <module>
    sys.exit(load_entry_point('gh-search', 'console_scripts', 'gh-search')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/augustd/Documents/Dev/gh-search/ghsearch/cli.py", line 82, in cli
    run(
  File "/Users/augustd/Documents/Dev/gh-search/ghsearch/main.py", line 48, in run
    results = gh_search.get_filtered_results(query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/augustd/Documents/Dev/gh-search/ghsearch/gh_search.py", line 80, in get_filtered_results
    exclude_reason = self._should_exclude(result)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/augustd/Documents/Dev/gh-search/ghsearch/gh_search.py", line 97, in _should_exclude
    if not result_filter(result):
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/augustd/Documents/Dev/gh-search/ghsearch/filters.py", line 25, in __call__
    content = result.decoded_content.decode("utf-8")
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/github/ContentFile.py", line 59, in decoded_content
    assert self.encoding == "base64", "unsupported encoding: %s" % self.encoding
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: unsupported encoding: none
```

**Comment by janeklb** [comment]
Apologies for the very slightly delayed reply.. 

Could you please share the query that produced these results?
